"""initial schema

Revision ID: b3b280a6e3b8
Revises: 
Create Date: 2026-06-20 10:10:58.245603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3b280a6e3b8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.alter_column('pic_url',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('article_type',
               existing_type=sa.VARCHAR(length=64),
               nullable=False,
               existing_server_default=sa.text("'other'"))
        batch_op.alter_column('article_type_reason',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('activity_kind',
               existing_type=sa.VARCHAR(length=64),
               nullable=False,
               existing_server_default=sa.text("'general_event'"))
        batch_op.alter_column('activity_kind_reason',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('is_event_related',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('relevance_reason',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('event_time_status',
               existing_type=sa.VARCHAR(length=64),
               nullable=False,
               existing_server_default=sa.text("'unknown'"))
        batch_op.alter_column('retention_decision',
               existing_type=sa.VARCHAR(length=64),
               nullable=False,
               existing_server_default=sa.text("'keep'"))
        batch_op.alter_column('user_keep',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('cover_image',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('performance_type',
               existing_type=sa.VARCHAR(length=128),
               nullable=False,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('performance_name',
               existing_type=sa.VARCHAR(length=512),
               nullable=False,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('performer',
               existing_type=sa.VARCHAR(length=512),
               nullable=False,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('ticket_info',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('lecture_topic',
               existing_type=sa.VARCHAR(length=512),
               nullable=False,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('speaker_title',
               existing_type=sa.VARCHAR(length=512),
               nullable=False,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('lecture_series',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('competition_name',
               existing_type=sa.VARCHAR(length=512),
               nullable=False,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('competition_type',
               existing_type=sa.VARCHAR(length=128),
               nullable=False,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('deadline',
               existing_type=sa.VARCHAR(length=128),
               nullable=False,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('prize_info',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('registration_url',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('registration_deadline',
               existing_type=sa.VARCHAR(length=128),
               nullable=False,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('participant_limit',
               existing_type=sa.VARCHAR(length=128),
               nullable=False,
               existing_server_default=sa.text("('')"))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('participant_limit',
               existing_type=sa.VARCHAR(length=128),
               nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('registration_deadline',
               existing_type=sa.VARCHAR(length=128),
               nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('registration_url',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('prize_info',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('deadline',
               existing_type=sa.VARCHAR(length=128),
               nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('competition_type',
               existing_type=sa.VARCHAR(length=128),
               nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('competition_name',
               existing_type=sa.VARCHAR(length=512),
               nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('lecture_series',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('speaker_title',
               existing_type=sa.VARCHAR(length=512),
               nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('lecture_topic',
               existing_type=sa.VARCHAR(length=512),
               nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('ticket_info',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('performer',
               existing_type=sa.VARCHAR(length=512),
               nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('performance_name',
               existing_type=sa.VARCHAR(length=512),
               nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('performance_type',
               existing_type=sa.VARCHAR(length=128),
               nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('cover_image',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('user_keep',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('retention_decision',
               existing_type=sa.VARCHAR(length=64),
               nullable=True,
               existing_server_default=sa.text("'keep'"))
        batch_op.alter_column('event_time_status',
               existing_type=sa.VARCHAR(length=64),
               nullable=True,
               existing_server_default=sa.text("'unknown'"))
        batch_op.alter_column('relevance_reason',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('is_event_related',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('activity_kind_reason',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('activity_kind',
               existing_type=sa.VARCHAR(length=64),
               nullable=True,
               existing_server_default=sa.text("'general_event'"))
        batch_op.alter_column('article_type_reason',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('article_type',
               existing_type=sa.VARCHAR(length=64),
               nullable=True,
               existing_server_default=sa.text("'other'"))

    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.alter_column('pic_url',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))

    # ### end Alembic commands ###
